// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJY8XLlb5Bhsc1hd4pnB14qq6luQ-W9I',
    appId: '1:862971153777:android:227b91fdd8a5f36fabbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    storageBucket: 'fintrack-gt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJY8XLlb5Bhsc1hd4pnB14qq6luQ-W9I',
    appId: '1:862971153777:ios:227b91fdd8a5f36fabbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    storageBucket: 'fintrack-gt.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiFV7SkWlVeVZ2xGwPMpc8oq6MfRYbNMM',
    appId: '1:862971153777:web:59674df0ba92a1e9abbad0',
    messagingSenderId: '862971153777',
    projectId: 'fintrack-gt',
    authDomain: 'fintrack-gt.firebaseapp.com',
    storageBucket: 'fintrack-gt.firebasestorage.app',
  );
}
